# Generated by Django 4.2.6 on 2023-10-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_rename_alunos_aluno_rename_cursos_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
