# Generated by Django 4.2.6 on 2023-10-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produto',
        ),
    ]
